### ISSUE TITLE
Activate AppVeyor CI

### ISSUE THREAD

**Issue by martinRenou** [pybind/pybind11_json#8]
@wjakob or @SylvainCorlay would you mind activating AppVeyor CI for this repo?

**Comment by wjakob** [comment]
Hi @martinRenou,

I pushed the 'add' button in my AppVeyor, but then it got added under my account (https://ci.appveyor.com/project/wjakob/pybind11-json). This is probably not what you wanted, right? Out of curiosity, are you able to add it yourself? (Since you are the administrator of this repository).

Best,
Wenzel

**Comment by martinRenou** [comment]
Maybe you need to select the pybind orgnization on this dropdown button?

![test](https://user-images.githubusercontent.com/21197331/66300655-f2d22280-e8f5-11e9-86a4-2f93c28b20b6.png)

It seems that I can only add my fork too

**Comment by wjakob** [comment]
https://ci.appveyor.com/project/pybind/pybind11-json

**Comment by martinRenou** [comment]
Thanks! :)

**Comment by SylvainCorlay** [comment]
👍 happy to see pybind11-json move to the `pybind11` github organization.
